version: "3"

services:
  dns:
    image: ragibkl/bancuh-dns
    build:
      context: .
    restart: always
    environment:
      CONFIG_URL: /data/configuration.yaml
      PORT: 53
      # FORWARDERS: "1.1.1.1,1.0.0.1"
      # FORWARDERS_PORT: "53"
    volumes:
      - ./data:/data
    ports:
      - 1153:53/tcp
      - 1153:53/udp
