version: "3"

services:
  dns:
    image: ragibkl/bancuh_dns
    build:
      context: .
    restart: always
    volumes:
      - ./data:/data
    command: -c /data/configuration.yaml -f 1.1.1.1,1.0.0.1
    ports:
      - 1153:53/tcp
      - 1153:53/udp
