version: "3"

services:
  bind:
    image: ragibkl/bancuh-bind
    restart: always
    ports:
      - 1154:53/tcp
      - 1154:53/udp

  dns:
    image: ragibkl/bancuh-dns
    build:
      context: .
    restart: always
    environment:
      CONFIG_URL: /data/configuration.yaml
      FORWARDERS: "127.0.0.1"
      FORWARDERS_PORT: "1154"
    volumes:
      - ./data:/data
    ports:
      - 1153:53/tcp
      - 1153:53/udp
